name: CI
on:
  pull_request:
    branches:
      - "*"

jobs:
  validate-protobuf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Install buf command
        env:
          BIN: /usr/local/bin
          VERSION: 1.25.0
        run: |
          curl -sSL "https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)" -o "${BIN}/buf"
          chmod +x "${BIN}/buf"

      - name: Check lint
        run: buf lint

      - name: Check format
        run: buf format --exit-code

  check-buildable:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Check buildable
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build
