name: CI
on:
  pull_request:
    branches:
      - "*"

jobs:
  validate-protobuf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Install buf command
        env:
          BIN: /usr/local/bin
          VERSION: 1.25.0
        run: |
          curl -sSL "https://github.com/bufbuild/buf/releases/download/v${VERSION}/buf-$(uname -s)-$(uname -m)" -o "${BIN}/buf"
          chmod +x "${BIN}/buf"

      - name: Check lint
        run: buf lint

      - name: Check format
        run: buf format --exit-code

  check-buildable-for-java:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Build stub codes
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

  check-buildable-for-typescript:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Install protoc-gen-js
        run: |
          curl -Lo protobuf-javascript.zip https://github.com/protocolbuffers/protobuf-javascript/releases/download/v3.21.2/protobuf-javascript-3.21.2-linux-x86_64.zip
          unzip -j protobuf-javascript.zip bin/protoc-gen-js -d /usr/local/bin
          rm protobuf-javascript.zip
          chmod +x /usr/local/bin/protoc-gen-js

      - name: Install protoc-gen-grpc-web
        run: |
          curl -Lo protoc-gen-grpc-web https://github.com/grpc/grpc-web/releases/download/1.4.2/protoc-gen-grpc-web-1.4.2-linux-x86_64
          mv protoc-gen-grpc-web /usr/local/bin/protoc-gen-grpc-web
          chmod +x /usr/local/bin/protoc-gen-grpc-web

      - name: Setup node 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Copy package.json
        run: |
          cp package.template.json package.json

      - name: Install dependencies
        run: npm install

      - name: Build stub codes
        run: |
          protoc -Isrc/main/proto/ --js_out=import_style=commonjs,binary:. --grpc-web_out=import_style=commonjs+dts,mode=grpcwebtext:. $(find src/main/proto -iname "*.proto")


  check-buildable-for-csharp:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - name: Install protoc-gen-grpc
        shell: bash
        run: |
          curl -Lo grpc-tools.zip https://packages.grpc.io/archive/2022/04/67538122780f8a081c774b66884289335c290cbe-f15a2c1c-582b-4c51-acf2-ab6d711d2c59/csharp/Grpc.Tools.2.47.0-dev202204190851.nupkg
          unzip -j grpc-tools.zip tools/linux_x64/grpc_csharp_plugin -d /usr/local/bin
          rm grpc-tools.zip
          mv /usr/local/bin/grpc_csharp_plugin /usr/local/bin/protoc-gen-grpc
          chmod +x /usr/local/bin/protoc-gen-grpc

      - name: Build stub codes
        shell: bash
        run: |
          mkdir Runtime
          protoc -Isrc/main/proto/ --csharp_out=./Runtime --csharp_opt=base_namespace=WeddingCamp.ProtoBuf --grpc_out=./Runtime $(find src/main/proto -iname "*.proto")
