name: Publish
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  publish-nuget-package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1

      - name: Publish to maven
        uses: gradle/gradle-build-action@v2
        with:
          arguments: publish
